

apiVersion: v2
name: mychart
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
dependencies:
- name: kyverno
  version: 3.5.1
  repository: "https://kyverno.github.io/kyverno/"